server:
  port: 8080

# H2
spring:
  # profiles:
    # active: dev

  # mvc:
  #   pathmatch:
  #     matching-strategy: ANT_PATH_MATCHER
  
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true





  